services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/usr/src/app
    networks:
      - app-network
    depends_on:
      - pgsql

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.development
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - PORT=5173
    volumes:
      - ./web:/app
    depends_on:
      - api
    networks:
      - app-network

  pgsql:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-course
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
