services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.production
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
      - PORT=5173
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
