services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.development
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - PORT=5173
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
